build: false

platform:
  - x64

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA_DIRNAME: C:\Miniconda36-x64

    - PYTHON_VERSION: 3.5
      MINICONDA_DIRNAME: C:\Miniconda35-x64

    - PYTHON_VERSION: 3.4
      MINICONDA_DIRNAME: C:\Miniconda34-x64

matrix:
  fast_finish: false

init:
  - ECHO %PYTHON_VERSION% %MINICONDA_DIRNAME%

install:
  - cmd: set "PATH=%MINICONDA_DIRNAME%;%MINICONDA_DIRNAME%\\Scripts;%PATH%"
  - cmd: conda config --set always_yes true
  - cmd: conda update --quiet conda
  - cmd: conda info --all
  - cmd: conda create --quiet --name conda-env-%PYTHON_VERSION% python=%PYTHON_VERSION%
  - cmd: activate conda-env-%PYTHON_VERSION%
  - cmd: pip install --disable-pip-version-check --user --upgrade pip
  - cmd: pip install -e .
  - cmd: pip install pytest pytest-xdist

test_script:
  - cmd: pytest --color=yes -n 2 -sv
